spring:
    datasource:
        database: cdctest
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: myroot
        url: jdbc:mysql://localhost:3306/cdctest?useSSL=false
        username: NewUsername
