spring:
    datasource:
        database: cdctest
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/cdctest?useSSL=false
        username: root
management:
  endpoints:
    web:
      exposure:
        include: "*"